name: Cromwell Test Run

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write

jobs:
  testrun:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      -
        name: Pull Cromwell Jarfile
        run: wget -q https://github.com/broadinstitute/cromwell/releases/download/86/cromwell-86.jar
      -
        name: Execute Test Run of WDL Workflow
        run: java -jar cromwell-86.jar run fastq-to-cram.wdl --inputs fastq-to-cram-inputs.json --options fastq-to-cram-options.json



