name: Docker Build and Upload CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      -
        name: Build and Push
        run: |
          wget https://github.com/broadinstitute/cromwell/releases/download/86/womtool-86.jar
          java -jar womtool-86.jar validate *.wdl



